### ISSUE TITLE
attempt to index field 'sorting' (a nil value)

### ISSUE THREAD

**Issue by ghost** [zjp-CN/nvim-cmp-lsp-rs#7] opened 2024-08-15 02:42 UTC
Please add better examples.

```
Failed to run `config` for nvim-cmp

/home1/avdb13/.config/nvim/lua/init.lua:84: attempt to index field 'sorting' (a nil value)

# stacktrace:
  - ~/.config/nvim/lua/init.lua:84 _in_ **values**
  - /cmp-cmdline/after/plugin/cmp_cmdline.lua:1
  - vim/_editor.lua:0 _in_ **cmd**
  - ~/.config/nvim/lua/init.lua:15
  - lua:1
  ```

**Comment by zjp-CN** [comment] 2024-08-15 04:13
Currently, this plugin doesn't work as it initially did due to some API breakages. And I may have not much time to fix it up in near future. Sorry for the bad experience.

**Comment by ghost** [comment] 2024-08-15 05:49
Can you point me at the commit that broke the API?

**Comment by 0xAdk** [comment] 2024-08-18 19:03
The issue is the default config tries to index `opts.sorting` without ensuring it exists, ditto for `ipairs(opts.sources)`
```lua
opts = function(_, opts)
	local cmp_lsp_rs = require 'cmp_lsp_rs'
	local comparators = cmp_lsp_rs.comparators
	local compare = require 'cmp'.config.compare

	opts.sorting = opts.sorting or {}
	opts.sorting.comparators = {
		compare.exact,
		compare.score,
		-- comparators.inherent_import_inscope,
		comparators.inscope_inherent_import,
		comparators.sort_by_label_but_underscore_last,
	}

	opts.sources = opts.sources or {}
	for _, source in ipairs(opts.sources) do
		cmp_lsp_rs.filter_out.entry_filter(source)
	end

	return opts
end,
```

**Comment by zjp-CN** [comment] 2024-08-19 01:13
@0xAdk Thanks for the suggestion. I'm closing this.

**Closed as completed** 2024-08-19 01:13 UTC
